config/routes.rb
Mediadrawer::Rails::Engine.routes.draw do
  scope :api, defaults: {format: :json} do
    root to: 'application#index', :defaults => { :format => 'html' }
    resources :media, only: [:index, :show, :create, :update, :destroy]
    resources :folders, only: [:index, :create, :update, :destroy]
  end
end

app/models/mediadrawer/folder.rb
module Mediadrawer
  class Folder < ActiveRecord::Base
    has_many :media_files, :class_name=> 'Media', foreign_key: 'folder_id', dependent: :destroy
    has_many :children, :class_name=>"Mediadrawer::Folder", foreign_key: "parent_id", dependent: :destroy
    belongs_to :parent, :class_name=>"Mediadrawer::Folder", foreign_key: "parent_id" 

    after_initialize :set_defaults

    scope :root, -> { find_or_create_by name: 'root_path' }

    def set_defaults
      if self.name != 'root_path'
        self.parent ||= Folder.root
      end
    end

    def name=(v)
      write_attribute :name, v.to_s.parameterize
    end

    def path
      return '' if parent.nil?
      return name if parent.path == ''
      "#{parent.path}/#{name}"
    end

    def self.discover(path=nil)
      folders = path.to_s.split '/'
      if folders.empty?
        Folder.root
      else
        folders.reduce(Folder.root) do |current_folder, folder_name|
          next current_folder if folder_name.empty?
          folder = Folder.find_by parent: current_folder, name: folder_name
          if folder
            folder
          else
            break
          end
        end
      end
    end
  end
end

app/models/mediadrawer/media.rb
module Mediadrawer
  class Media < ActiveRecord::Base
    include Magick
    belongs_to :folder, touch: true
    has_many :media_sizes, :class_name=> 'MediaSizes', foreign_key: 'mediadrawer_media_id', dependent: :destroy
    after_initialize :set_defaults

    after_destroy :delete_file

    DEFAULT_SIZE = 'original'

    def delete_file
      s3 = S3.new
      unless is_image?
        s3.delete path
      else
        s3.delete self.path(DEFAULT_SIZE)
        Mediadrawer.config['sizes'].each do |size_name, size|
          s3.delete self.path(size_name)
        end
      end
    end

    def type
      unless is_image?
        'file'
      else
        'image'
      end
    end

    def is_image?
      mime_type =~ /image/
    end

    def set_defaults
      self.folder ||= Folder.root
    end

    def name=(v)
      v = v.to_s
      extension = v.split('.').last
      name = v.split('.')[0...-1].join '.'
      write_attribute :name, "#{name.parameterize}.#{extension}"
    end

    def path(size=DEFAULT_SIZE)
      file_path_part = size ? "#{size}/#{name}" : name
      if self.folder.path.empty?
        file_path_part
      else
        "#{self.folder.path}/#{file_path_part}"
      end
    end

    def url
      url_for
    end

    def url_for(size=DEFAULT_SIZE)
      cache_key = "#{self.id}:#{self.updated_at}:#{size}:#{Mediadrawer.config[:asset_host]}"
      ::Rails.cache.fetch cache_key do
        remote_path = self.path(size)

        if Mediadrawer.config['asset_host']
          "#{Mediadrawer.config['asset_host']}/#{remote_path}"
        else
          s3 = S3.new
          s3[remote_path].public_url.to_s
        end
      end
    end

    def upload(content, sizes=[])
      unless content.kind_of? Tempfile
        file = Tempfile.new(self.name)
        file.binmode
        file.write content
        file.close
      else
        file = content
      end

      FileUploader.upload(file, self.path(DEFAULT_SIZE))
      if is_image?
        ImageResizer.resize(file, sizes) do |resized_file, size_name, size|
          FileUploader.upload(resized_file, self.path(size_name))
        end
      end
      self.save
    end
  end
end

app/models/mediadrawer/media_sizes.rb
module Mediadrawer
  class MediaSizes < ActiveRecord::Base
    belongs_to :media
  end
end

app/controllers/mediadrawer/application_controller.rb
module Mediadrawer
  class ApplicationController < ActionController::Base
    def index
      render :layout => false, format: :html
    end
  end
end

app/controllers/mediadrawer/folders_controller.rb
module Mediadrawer
  class FoldersController < ApplicationController
    respond_to :json

    def index
      path = params[:path] || ''
      @recursive = params[:recursive] || '0'
      @folder = Folder.discover(path)
      unless @folder
        head 404
      end
    end

    def update
      @folder = Folder.find params[:id]
      @folder.name = params[:name]
      if @folder.save
        render partial: 'item', locals: { item: @folder }
      else
        head 422
      end
    end

    def destroy
      Folder.find(params[:id]).destroy
      head 200
    end

    def create
      @folder = Folder.new
      @folder.name = params[:name]
      if @folder.save
        render partial: 'item', locals: { item: @folder }
      else
        head 422
      end
    end
  end
end

app/controllers/mediadrawer/media_controller.rb
module Mediadrawer
  class MediaController < ApplicationController
    respond_to :json

    def create
      @media = Media.new
      @media.folder = Folder.discover(params[:path])
      if params[:file]
        file = params[:file]

        @media.mime_type = file.content_type
        @media.name = file.original_filename
        @media.upload(file.tempfile, Mediadrawer.config['sizes'])
      elsif params[:link]
        link = params[:link]
        @media.name = File.basename(link)
        response = open(link, ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE)
        @media.mime_type = response.content_type
        @media.upload response.read
      end
      render :show
    end

    def destroy
      Media.find(params[:id]).destroy
      head 200
    end

    def update
      @media = Media.find params[:id]
      @media.update alt: params[:alt]
      render :show
    end

    def show
      @sizes = params[:imageSizes]
      @media = Media.find params[:id]
    end

    def index
      @folder = Folder.discover(params[:path])
      @media_files = @folder.media_files
      if params[:type]
        @media_files = @media_files.where('mime_type like ?', ["%#{params[:type]}%"])
      end
      @media_files = @media_files.page(params[:page]).per(params[:per])
      @folder.media_files
    end
  end
end

app/controllers/mediadrawer/rails/application_controller.rb
module Mediadrawer
  module Rails
    class ApplicationController < ActionController::Base
      def index

      end
    end
  end
end

app/helpers/mediadrawer/application_helper.rb
module Mediadrawer
  module ApplicationHelper
  end
end

app/views/layouts/mediadrawer/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mediadrawer</title>
  <%= stylesheet_link_tag    "mediadrawer/application", media: "all" %>
  <%= javascript_include_tag "mediadrawer/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mediadrawer/application/_containers.html.erb
<div class="row">
  <div class="col-xs-11">
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#md-files" role="tab" data-toggle="tab">Arquivos</a></li>
      <li><a href="#md-upload" role="tab" data-toggle="tab">Upload</a></li>
    </ul>
  </div>
</div>

<div class="sidebar-wrapper">
  <div class='folder-menu' data-folder-menu>
    <ul></ul>
  </div>
</div>

<div class="tab-content">

  <div class="tab-pane active" id="md-files" class="files">
    <div class="btn-group filter-actions" role="group" aria-label="Actions" data-toggle="buttons">
      <label class="btn active" filter="">
        <input type="radio" checked> Todos
      </label>
       <label class="btn" filter="image">
        <input type="radio" checked> Imagens
      </label>
       <label class="btn" filter="application">
        <input type="radio" checked> Arquivos
      </label>
    </div>
    <div class='info-panel'></div>
    <div class='files-container' data-image-container>
      <ul class="thumbnails"></ul>
    </div>
  </div>

  <div class="tab-pane" id="md-upload" class="upload">
    <form action="<%= media_index_path %>" method="POST" enctype="multipart/form-data">
      <input name="imageSizes" data-image-sizes="" type="hidden">
      <div class="row">
        <div class="col-xs-8">
          <div class="row">
            <div class="col-xs-12">
              <input type="file" name="file" class="file">
            </div>
          </div>
          <hr />
          <div class="row">
            <div class="col-xs-12">
              URL: <input type="url" name="link" class="form-control" placeholder="http://exemplo.com">
            </div>
          </div>
        </div>
        <div class="col-xs-4">
          <button class="btn btn-primary" data-async-submit data-success-fn="uploadSuccess" data-progress-fn='uploadProgress'>Upload</button>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <progress max="100" style="display: none"></progress>
        </div>
      </div>
    </form>
  </div>

</div>

app/views/mediadrawer/application/index.html.erb
<div id="mediadrawer" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title">Mediadrawer</h4>
      </div>
      <div class="modal-body">
        <%= render 'containers' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn pull-left" data-add-folder>Nova pasta</button>
        <button data-select-image class="btn btn-primary"
          data-mediadrawer-select>Selecionar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->